### ISSUE TITLE
Error appears when editing image block inside rich text editor in Presentation mode

### ISSUE THREAD

**Issue by thomasKn** [sanity-io/visual-editing#1020]
**Describe the bug**

Using presentation mode in a Remix app the following error shows up when I try to edit an image block `Cannot get the leaf node at path [] because it refers to a non-leaf node` (see screenshot below).
I can create the block and select the image, but if I refresh the page and try to edit the image block, the error shows up.
The error only appears in presentation mode, there is no issue while updating the block from the Structure view.

**To Reproduce**

1. Clone this [Clean Remix template](https://github.com/thomasKn/sanity-template-remix-clean)
2. Launch the app
3. Go to `/post/hello-world`
4. Open presentation mode by clicking on the portable text overlay
5. Try to edit or open the image block
6. The error shows up

**Expected behavior**

Should work the same as the Structure view.

**Screenshots**
![Capture-2024-02-27-183518](https://github.com/sanity-io/visual-editing/assets/10447155/e24bb456-04e6-47d2-bdc7-bb966c20aa80)

**Which versions of Sanity are you using?**
"sanity": "3.30.1"
"@portabletext/react": "3.0.11"
"@sanity/client": "6.15.0"
"@sanity/image-url": "1.0.2"
"@sanity/react-loader": "1.9.0"
"@sanity/visual-editing": "1.5.2"

**What operating system are you using?**
macOS 14.3.1

**Which versions of Node.js / npm are you running?**
10.2.4
v21.6.2

**Additional context**

**Comment by thomasKn** [comment]
I updated sanity to `3.33.0` and the error is gone.

**Comment by rdunk** [comment]
Thanks for the update! Please feel free to report back if the issue resurfaces.
