### ISSUE TITLE
core-loader@1.5.1 breaks loaders used on browser client

### ISSUE THREAD

**Issue by narration-sd** [sanity-io/visual-editing#1051]
On update to `react-loader@1.9.1/core-loader@1.5.1`,  `useQuery()` will 100% fail with `error` value: `'f.instance is undefined',` after having been set up properly via `createQueryStore({client: validClent, ssr: false}` beforehand. 

Pinning versions back to prior `1.9.0/1.5.0` returns to nice Presentation operation overall,  as has been normal for months.

Analyzing the code, the problem appears to begin in this setup point, whose attribute name fits the visible portion in the error message: https://github.com/sanity-io/visual-editing/blob/2275739e74e85993ce97782e5e877bbf80983740/packages/core-loader/src/index.ts#L137

...where this line in the function called requires an `unstable_serverClien`t: https://github.com/sanity-io/visual-editing/blob/2275739e74e85993ce97782e5e877bbf80983740/packages/core-loader/src/index.ts#L123

However, since we are client-only, there is no `unstable_serverClient` value, and even if we were to try to set one, the code for that prevents it absolutely for runtime client, non-SSR situations.:  https://github.com/sanity-io/visual-editing/blob/2275739e74e85993ce97782e5e877bbf80983740/packages/core-loader/src/index.ts#L244

**solution possible**

The PR which causes this appears to focus on server-side usage (https://github.com/sanity-io/visual-editing/pull/1034), but it seems it should be straightforward to make its intents compatible also for client-side. 

Since `createQueryStore()` will have a Sanity cliient available when used client-side, it appears a simple choice can be made to use its possibly re-configured instance for the cache setup in that case, beginning from here: https://github.com/sanity-io/visual-editing/blob/2275739e74e85993ce97782e5e877bbf80983740/packages/core-loader/src/index.ts#L93

**To Reproduce**

1. have an operating Visual Edit (Presentation) previewer that runs on browser client only
2. install the versions as above

**Expected behavior**
Preview operations initialize and operate fine in full range of Presentation activities

** Fault result**

No data received from `useQuery()`, returning error:  `f.instance is undefined`, with the consequence that all preview operations fail.

**Environment*

$ sanity versions
@sanity/cli (global)  3.29.1 (latest: 3.30.1)
@sanity/image-url      1.0.2 (up to date)
@sanity/react-loader   1.9.1 (up to date)
@sanity/ui             2.0.7 (up to date)
@sanity/vision        3.30.1 (up to date)
sanity                3.30.1 (up to date)

on Windows 11 latest, $ npm -v && node -v
10.2.4
v20.11.1

**No Security issues**

**Comment by stipsan** [comment]
Let me know if `npm install @sanity/core-loader@latest` solves it @narration-sd! :)

**Comment by stipsan** [comment]
Confirmed fixed :D
