### ISSUE TITLE
CORS errors in production, breaking live updates

### ISSUE THREAD

**Issue by ndimatteo** [sanity-io/visual-editing#1079]
**Describe the bug**

After following your guide here: https://www.sanity.io/guides/nextjs-live-preview and deploying to `sanity.studio` with `sanity deploy` the studio has tons of CORS errors (see screenshot below). This is also causing live updates to stop streaming to the preview pane.

**To Reproduce**

1. Follow the guide above
2. Deploy to Sanity via `sanity deploy`
3. Open the studio in production

**Expected behavior**

The visual editing tool to work in production as it does in development.

**Screenshots**
![image](https://github.com/sanity-io/visual-editing/assets/737188/4ed13d3e-2064-474e-8f44-876baf95e117)
**VIDEO**
https://github.com/sanity-io/visual-editing/assets/737188/69bdc000-b6e9-495e-8143-80d3511a8ab4

<br />

**Which versions of Sanity are you using?**

```bash
@sanity/code-input                4.1.3 (up to date)
@sanity/color-input               3.1.1 (up to date)
@sanity/eslint-config-studio      3.0.1 (up to date)
@sanity/orderable-document-list   1.2.1 (up to date)
@sanity/overlays                 2.3.24 (up to date)
@sanity/react-loader              1.9.3 (up to date)
@sanity/ui                        2.0.7 (up to date)
@sanity/vision                   3.32.0 (up to date)
sanity                           3.32.0 (up to date)
```

**What operating system are you using?**

MacOS v13.2.1 (22D68)

**Which versions of Node.js / npm are you running?**

v9.6.7
v18.17.0

**Comment by Henkisch** [comment]
I have bumped into this as well and can't seem to find a solution.

My presentation preview pane is not even able to load, it just crashes right away when draft mode is enabled it seems.

**Comment by rdunk** [comment]
Related issue: https://github.com/sanity-io/sanity/issues/6148

Can you confirm these CORS errors only appear on preflight requests to the following URL?

`https://api.sanity.io/v2023-12-11/journey/comments?tag=sanity.studio`

**Comment by rdunk** [comment]
Closing this as it looks to be an upstream studio issue that has been fixed. Please reopen if the errors persist.
