### ISSUE TITLE
[Hydrogen Vite] Error "setServerClient function is server only" gets called on server

### ISSUE THREAD

**Issue by thomasKn** [sanity-io/visual-editing#1085]
**Describe the bug**

I'm trying to setup `@sanity/react-loader` in an Hydrogen project running Vite.
Dev server fails to launch with the following error:
```Error: The `setServerClient` function is server only.```

`setServerClient` is called inside a `*.server.ts` Remix file so I'm pretty sure [server and client code is correctly split](https://remix.run/docs/en/main/future/vite#splitting-up-client-and-server-code). 

**To Reproduce**

1. Clone https://github.com/thomasKn/hydrogen-vite
2. `npm run dev`

**Which versions of Sanity are you using?**
```
 "@sanity/client": "^6.15.3"
 "@sanity/react-loader": "^1.9.3"
```

**What operating system are you using?**

`macOS 14.3.1`

**Which versions of Node.js / npm are you running?**

```
10.2.4
v21.6.2
```

**Comment by thomasKn** [comment]
Seems like the `oxygen()` Vite plugin is using the `target: "webworker"` option [here](https://github.com/Shopify/hydrogen/blob/e50f4349b665a1ff547a8d6229a6269157d867bd/packages/cli/src/lib/vite/plugins.ts#L105), which makes Vite grab the browser bundle of `@sanity/react-loader`. More context [here](https://github.com/vitejs/vite/issues/6401).

So I updated `index.browser.ts` in react-loader to be the same as `index.ts` and it works.
```tsx
export * from './createQueryStore/universal'
export * from './useEncodeDataAttribute'
export * from '@sanity/core-loader/create-data-attribute'
```

Is there any way to tell Vite to use the universal bundle? Or should the react-loader be able to detect Vite worker environment?

**Comment by stipsan** [comment]
Hi @thomasKn, could you give https://github.com/sanity-io/visual-editing/releases/tag/react-loader-v1.9.8 a try? 😄

**Comment by thomasKn** [comment]
Thanks @stipsan it works perfectly!
