### ISSUE TITLE
Documentation on this is sorely inadequate

### ISSUE THREAD

**Issue by sangrepura** [sanity-io/visual-editing#1206]
**Is your feature request related to a problem? Please describe.**

I have been unable to get this working with your starter templates (e.g. [Nextjs Personal Website](https://www.sanity.io/templates/personal-website-with-built-in-content-editing) and others) and the documentation for several reasons:
1. There is no mention of the @vercel/stega requirement for this feature and the fact that this apparently requires an Enterprise Subscription
    * See: [Visual Editing](https://www.sanity.io/docs/visual-editing)
    *  [This doc](https://www.sanity.io/docs/loaders-and-overlays) also doesn't disclose this and is outdated - providing instructions to use deprecated packages (@sanity/overlay)
    * The react-loader docs don't mention this either and only show a stega option in the [code exmple](https://github.com/sanity-io/visual-editing/blob/main/packages/react-loader/README.md)
    * When I ran the above mentioned starter my Content editor always shows an error: `The top menu isn't linking to the home page. This might make it difficult for visitors to navigate your site.`
      The console shows a network failure at `
https://1i8o4ufe.api.sanity.io/v2024-03-12/data/listen/production`

**Describe the solution you'd like**
I am only evaluating this product because I am looking for a new CMS, but the docs are not clear and concise for new developers to get started with Live Previews on the latest version. Nor are you letting people know not to waste our time with it if you don't have Vercel Enterprise. 

Additionally, there are no functioning templates for NextJs1 14 with App Router that we can just deploy and see working without errors.

**Describe alternatives you've considered**

I looked at many templates and a lot of your documentation and a lot of it is not up to date with your latest features - nor is it clear what version of a piece of documentation I am looking at.  See Vercel's NextJs docs for a reference.  They are clear about a page being about App Router vs Pages Router

**Additional context**

Fresh deploy of template:

![Uploading image.png…]()

**Comment by rdunk** [comment]
Hello, thanks for the feedback. I think it's a fair assessment that the docs are currently lacking in some areas and also lagging behind the current versions. We are currently working on revamping them as we've just stabilised a lot of APIs, but I know that's not particularly useful for you right now.

Can I ask, are you specifically trying to implement Vercel Visual Editing?

Visual Editing using Presentation tool is available for all plans, it does use the `@vercel/stega` package under the hood but installing that does not require a Vercel or Sanity enterprise plan.

I can see that our messaging around the differences between Sanity and Vercel's visual editing offerings could definitely be clearer, so thanks for highlighting that.

**Comment by sangrepura** [comment]
Hi @rdunk, thank you for that response. When I deployed the template that I mentioned above and kept receiving the error: `The top menu isn't linking to the home page. This might make it difficult for visitors to navigate your site.`  I guess I presumed that it was because I wasn't a Vercel Enterprise customer.  I couldn't find anything in the docs or issue history as well.

Your CMS has a lot of potential, so I do hope that the docs improve.  Thanks again!

**Comment by stipsan** [comment]
>The top menu isn't linking to the home page. This might make it difficult for visitors to navigate your site.

@sangrepura [this is just a custom feature in the template](https://github.com/sanity-io/template-nextjs-personal-website/blob/73f89cafd159a5293b999fc1e671752521d179fb/sanity/plugins/locate.ts#L54-L57) and has nothing to do with any price plans. It's just warning you that you haven't added a Menu Item for your home page, look at this screenshot and the first item in the "Menu Item List" for how to make this warning go away:
![image](https://github.com/sanity-io/visual-editing/assets/81981/5ed15cef-6f46-42c0-b4ab-42a909c4a70c)

**Comment by kmelve** [comment]
Hi @sangrepura! Thanks for the feedback 🙇  

We have recently published more/better docs to bring visibility to things like Stega-encoding, make it clear that you can use Visual Editing on free plans, and more. We'll continue to improve the docs as the Visual Editing gets more features as well. Closing this as your questions have been seemingly been answered.
