### ISSUE TITLE
react-loader: Attempted import error: 'useEffect' is not exported from 'react' (imported as 't').

### ISSUE THREAD

**Issue by IlirEdis** [sanity-io/visual-editing#1377]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**
It seems that the new update of `@sanity/react-loader` (`v1.9.13`) doesn't like dynamic open graph image.
After updating my Sanity dependencies (check versions below) i got this error when deploying on Vercel.

**To Reproduce**

1. Update dependencies to the latest, especially `@sanity/react-loader` to `v1.9.13`
2. Create a dynamic `opengraph-image.tsx` on a dynamic route and fetch data in there using react-loader
3. Deploy to Vercel

**Expected behavior**

**Screenshots**

<img width="1840" alt="Screenshot 2024-04-20 at 15 23 10" src="https://github.com/sanity-io/visual-editing/assets/128377763/308d5651-2af9-4c53-ae7f-fff1c8b99412">

**Which versions of Sanity are you using?**

Run `sanity versions` in the terminal and copy-paste the result here.

```
@sanity/cli (global)        3.38.0 (up to date)
@sanity/code-input           4.1.4 (up to date)
@sanity/image-url            1.0.2 (up to date)
@sanity/preview-kit         5.0.45 (up to date)
@sanity/preview-url-secret  1.6.10 (up to date)
@sanity/react-loader        1.9.13 (up to date)
@sanity/vision              3.38.0 (up to date)
@sanity/visual-editing      1.8.14 (up to date)
sanity                      3.38.0 (up to date)
```

**What operating system are you using?**

MacOS Sonoma 14.4.1

**Which versions of Node.js / npm are you running?**

Run `npm -v && node -v` in the terminal and copy-paste the result here.

```
10.1.0
v20.9.0
```

**Additional context**

**Security issue?**

Any security issues should be submitted directly to [security@sanity.io](mailto:security@sanity.io). In order to determine whether you are dealing with a security issue, ask yourself these two questions:

- Can I access something that's not mine, or something I shouldn't have access to?
- Can I disable something for other people? If the answer to either of those two questions are "yes", then you're probably dealing with a security issue. Note that even if you answer "no" to both questions, you may still be dealing with a security issue, so if you're unsure, just email us at [security@sanity.io](mailto:security@sanity.io.

**Comment by IlirEdis** [comment]
Ok, it works with `client.fetch` directly. Thanks!

However, with `react-loader`:
It was working with `next v14.1.3` and `@sanity/react-loader v1.9.3`. 
Downgrading react-loader to 1.9.3 works again even with next v14.2.2.
Updating it again to `^1.9.13` not working and i get the same error at build time.

But this is not relevant anymore, at least for me :)

**Comment by stipsan** [comment]
How strange, must've been because we started shipping strict ESM compatible code so `next` started to detect the usage of `useEffect` consistently 🤔 

Glad it worked out! 👍
