### ISSUE TITLE
Copy link and open preview don't enable draft

### ISSUE THREAD

**Issue by mariusGundersen** [sanity-io/visual-editing#1590]
![image](https://github.com/sanity-io/visual-editing/assets/464152/6fe3abfb-7f7c-40ec-8b37-86fd0ec6f92e)

When using the presentation mode in Firefox the two buttons for sharing the page don't work as I would like. The `Copy link` button copies the link in the addressbar, and the `Open preview` opens the same url in a new tab (or window). They should include a secret and link to the `/enable-draft` url (or whatever was specified in the config under `previewUrl.previewMode.enable`). Having looked at the code it seems like the `Copy link` button attempts do to this, but it does not work in Firefox since `ClipboardItem` isn't enabled in Firefox. The `Open preview` however does not make any attempt to do it.

Having looked at the code for the `Copy link` button [here](https://github.com/sanity-io/visual-editing/blob/main/packages/presentation/src/preview/ShareUrlMenuItems.tsx#L103-L130) I don't see the reason why it is using a ClipboardItem. It only uses one mime-type, so it doesn't provide much value, IMO. It could just copy the generated url from `resolvePreviewUrl()` as text, which would simplify the implementation and it would work in all browsers.

I also don't see why the `Open preview` link can't use the same way to generate a preview url. Instead of generating the preview url and setting it as href it could rely on the `openPopup()` call made in the `onClick` handler, so that it only needs to call `createPreviewSecret()` once the link is clicked. Since this is an async task which could take a while it could use the same toast system as the `Copy link` button uses to inform the user of the pending popup.

It seems like it should be fairly easy to change these two to work as I the user expects.

**Comment by stipsan** [comment]
Unfortunately we can't wait with calling `navigator.clipboard.write` until after a promise is resolved. In our testing this fails on Safari for iOS, it has to be called within the same event as the onClick handler.
if you have an alternative implementation that works on iOS feel free to open a PR and we'll take a look. 

The `Open preview` feature works differently, it calls the `window.open` API and uses `postMessage` just like the iframe, giving it the ability to push updates with low latency. Thus it doesn't need to include the secret, that's what the `Copy link` feature is for.

An alternative feature could be that we render a read-only text input with the URL for FireFox (and whatever other browser that doesn't implement `ClipboardItem` API) in the popover, that includes the secret. We can then auto focus it and copy it to your clipboard when you tap on the input. Not sure if we can use autofocus.

In any case feel free to open a PR and we can continue the discussion there :)
