### ISSUE TITLE
Where can I find the source code for `@vercel/stega`

### ISSUE THREAD

**Issue by schalk-b** [sanity-io/visual-editing#1611]
https://www.sanity.io/docs/stega mentions that `@vercel/stega` is developed by Sanity. I can't seem to find the original source code anywhere. Is the repo uploaded on github anywhere?

**Comment by rdunk** [comment]
As far as I'm ware Vercel haven't open sourced the `@vercel/stega` package.

Would be best to reach out to them via GH or their support channels if you have specific questions about that package.
