### ISSUE TITLE
Overlays can not take you to fields under a collapsed fieldset

### ISSUE THREAD

**Issue by PikiLee** [sanity-io/visual-editing#1665]
**Describe the bug**
If a field is under a collapsed fieldset, clicking an overlay can not take you to the field though it does take you to the right document. The field will not be highlighted unless the fieldset has been expanded.

**To Reproduce**

1. Go to Presentation
2. Collapse a fieldset
3. Click an overlay that has content sourced from fields under the fieldset

**Expected behavior**

Clicking the overlay should expand the collapsed fieldset and highlight the corresponding field. 

**Screenshots**
https://github.com/sanity-io/visual-editing/assets/37203836/f02fdee9-a23b-425f-a9d2-c3f2d42a83d6

**Which versions of Sanity are you using?**

@sanity/cli (global)             3.46.1 (up to date)
@sanity/image-url                 1.0.2 (up to date)
@sanity/orderable-document-list   1.2.1 (up to date)
@sanity/preview-url-secret        1.6.7 (latest: 1.6.17)
@sanity/react-loader              1.9.9 (latest: 1.10.3)
@sanity/types                    3.45.0 (latest: 3.46.1)
@sanity/ui                        2.1.3 (latest: 2.3.6)
@sanity/vision                   3.37.2 (latest: 3.46.1)
@sanity/visual-editing            1.8.7 (latest: 2.1.5)
@sanity/webhook                   4.0.3 (latest: 4.0.4)
sanity                           3.46.1 (up to date)

**What operating system are you using?**
Mac os Sonoma 14.1.1

**Which versions of Node.js / npm are you running?**

pnpm 9.3.0
node v20.13.1

**Comment by rdunk** [comment]
Thanks, I can confirm this. Closing in favour of #1649 which we can use to track focus behaviour for fields in both groups and collapsed fieldsets.
