### ISSUE TITLE
[Hydrogen] Remix VisualEditing is performing a full reload on change

### ISSUE THREAD

**Issue by thomasKn** [sanity-io/visual-editing#2060]
**Describe the bug**

In Presentation mode, the Remix `VisualEditing` component is performing a full page reload when the content changes.
I'm using the `VisualEditing` component in a Hydrogen app.

**To Reproduce**

https://github.com/frontvibe/hydrogen-vite-sanity

**Screenshots**

https://github.com/user-attachments/assets/b5917edb-6dbb-4802-b8a9-991be1a23227

**Which versions of Sanity are you using?**

**@sanity/cli (global)**         3.62.2
**@sanity/preview-url-secret**    2.0.0
**@sanity/react-loader**        1.10.13
**@sanity/visual-editing**        2.4.1
**sanity**                       3.62.2

**What operating system are you using?**

macOS 15.0.1

**Which versions of Node.js / npm are you running?**

10.5.0
v20.12.0

**Comment by MatthewHager** [comment]
I am seeing the same exact behavior on Next 15.
