### ISSUE TITLE
[Presentation] Updates causes full page refreshing

### ISSUE THREAD

**Issue by JohnGemstone** [sanity-io/visual-editing#2087]
When updating content via Presentation v1.17.4+ the page fades to black multiple times (probably caused by refresh behaviour)

**To Reproduce**

1. `pnpm create next-app --example cms-sanity next-sanity-blog`
2. Create a post
3. Update the post via the Presentation panel

**Expected behavior**
Content to update without page fading to black

**Screen recordings**
[`@sanity/presentation@1.17.4`](https://github.com/sanity-io/visual-editing/releases/tag/presentation-v1.17.4):

https://github.com/user-attachments/assets/80f44d04-382f-4cfe-b3ea-3a0627c54d19

Panel updates as expected with `@sanity/presentation@1.17.3`:

https://github.com/user-attachments/assets/81c7b48a-0ac3-4d78-98e0-ba94111e52d2

**Which versions of Sanity are you using?**
```
@sanity/cli (global)        3.62.3 (up to date)
@sanity/assist               3.0.8 (up to date)
@sanity/icons                3.4.0 (up to date)
@sanity/image-url            1.1.0 (up to date)
@sanity/mutate              0.10.1 (up to date)
@sanity/presentation        1.17.7 (up to date)
@sanity/preview-url-secret   2.0.0 (up to date)
@sanity/util                3.62.3 (up to date)
@sanity/vision              3.62.3 (up to date)
@sanity/visual-editing       2.4.2 (up to date)
sanity                      3.62.3 (up to date)
```

**What operating system are you using?**
OSX + Chrome

**Which versions of Node.js / npm are you running?**
v22.0.0

**Comment by rdunk** [comment]
Thanks for the detailed report!

Would you mind installing https://github.com/sanity-io/visual-editing/releases/tag/presentation-v1.18.2 and letting me know if the issue persists?

**Comment by JohnGemstone** [comment]
Works perfect thanks for the fix!
