### ISSUE TITLE
"Open in studio"-links always open the root page.

### ISSUE THREAD

**Issue by dagstuan** [sanity-io/visual-editing#2166]
**Describe the bug**

In previous versions of presentation, clicking the "open in studio"-button in draftMode would take me to the page I'm standing on when I the presentation tool opens. But this no longer happens, if I click on "Open in studio"-button I'm always taken to `/` in the presentation tool regardless of where I was when I click the button. The correct document opens alongside the presentation tool, only the preview URL is incorrect.

<img width="1841" alt="image" src="https://github.com/user-attachments/assets/7e782ff2-b1e6-42e1-a6ea-a7423c7e1781">
<img width="872" alt="image" src="https://github.com/user-attachments/assets/13d4fc1f-af30-430f-a601-f5e8d544958e">

I believe this issue was introduced with PR #1809

**To Reproduce**

Setup a solution with visual editing. Open draft mode and click a link to "Open in studio" that's not on the root page.

**Expected behavior**

The presentation tool opening on the correct page.

**Which versions of Sanity are you using?**

@sanity/icons                3.4.0 (up to date)
@sanity/image-url            1.1.0 (up to date)
@sanity/preview-url-secret   2.0.3 (up to date)
@sanity/ui                  2.8.23 (up to date)
sanity                      3.64.1 (up to date)

**Comment by dagstuan** [comment]
Debugging a bit, it seems to work if I give Sanity a fully qualified `studioUrl` such as http://localhost:3000/studio.. But if I implement it like the [nextjs-template](https://github.com/sanity-io/template-nextjs-personal-website/blob/main/sanity/lib/api.ts#L33) and only give it `/draft`, the preview button will not open the correct preview page.

The crash seems to be this line: https://github.com/sanity-io/visual-editing/blob/main/packages/visual-editing/src/ui/ElementOverlay.tsx#L321

**Comment by stipsan** [comment]
Hi @dagstuan can you test https://github.com/sanity-io/visual-editing/releases/tag/visual-editing-v2.7.2 or https://github.com/sanity-io/next-sanity/releases/tag/next-sanity-v9.8.15 and see if it resolves it?

**Comment by dagstuan** [comment]
@stipsan works great now! Thanks for the quick fix!
