### ISSUE TITLE
BUG: Overlay cursors remain when the edit is disabled

### ISSUE THREAD

**Issue by mariusGundersen** [sanity-io/visual-editing#2179]
When hovering over elements the cursor is set to either `move` or `auto` from the code here: https://github.com/sanity-io/visual-editing/blob/10ecc2a791876501bb55aa92956d6c177f5b2a50/packages/visual-editing/src/controller.ts#L151

Unfortunately this is not cleaned up when edit is toggled up, which means the cursors look different when trying to navigate the page normally.

For example, we have set all `a:href` to have `cursor:pointer`, but with the overlay they get the default pointer. This means that when the overlay is disabled it looks like something is wrong, since they don't have the pointer they normally have. 

Worse yet is that for array items that can be rearranged they will have the `move` cursor even though they cannot be moved.

https://github.com/user-attachments/assets/a354fa37-c1a7-4c25-81a9-c6fa72637fa2

**Comment by rdunk** [comment]
Thanks for reporting! I've opened a PR with a potential fix https://github.com/sanity-io/visual-editing/pull/2181.

**Comment by rdunk** [comment]
#### Fixed in
https://github.com/sanity-io/visual-editing/pull/2181
#### Released in
https://github.com/sanity-io/visual-editing/releases/tag/presentation-v1.18.5
https://github.com/sanity-io/sanity/releases/tag/v3.65.0
