### ISSUE TITLE
@sanity/visual-editing@2.10.3 breaks Nuxt frontend

### ISSUE THREAD

**Issue by metaforx** [sanity-io/visual-editing#2265]
**Describe the bug**

Using Nuxt in combination with visual-editing dependency from @nuxtjs/sanity breaks Nuxt frontend when visual editing is enabled via config:

```js
    visualEditing: {
       token: process.env.NUXT_SANITY_VISUAL_EDITING_TOKEN,
       studioUrl: 'http://localhost:3333',
    },
```
Nuxt launches without errors, but the browser displays an error with react-compiler-runtime and interrupts JS execution, which also prevents visual editing from working properly.

```js
Uncaught SyntaxError: The requested module '/_nuxt/node_modules/.pnpm/react-compiler-runtime@19.0.0-beta-df7b47d-20241124_react@18.3.1/node_modules/react-compiler-runtime/dist/index.js?v=4212c007' does not provide an export named 'c' (at mutations.js?v=4212c007:1:8)
```

react-compiler-runtime/dist/index.js actually exports `c`

```js
//line 320
exports.c = c;
```

**To Reproduce**

1. Install fresh Nuxt Project
2. Add @nuxtjs/sanity
3. Add missing react dependency:  `pnpm add react-is@latest`
4. Add needed @sanity/visual-editing (otherwise nuxt complains on startup) : `pnpm add @sanity/visual-editing@latest`
5. Configure nuxt to use visualEditing (see description)

Or checkout: 
https://github.com/metaforx/sanity-io-visual-editing-react-compiler-bug

**Expected behavior**

Nuxt should run without error in frontend and visual editing should work via studio.

**Which versions of Sanity are you using?**

Not needed in Nuxt frontend.

**Which versions of Node.js / npm are you running?**

10.9.0
v22.12.0

**Comment by metaforx** [comment]
Not yet a perfect fix but a working solution and a resason for the problem.

The culprit it seems to be vite:

- The root project is trying to use vite@5.4.11.
- @sanity/visual-editing requires vite@^6.0.0

Reproduce:
1. Delete all node_modules and clear cache
2. Instead of pnpm use `npm install`
3. Greeted with error pointing towards differing vite versions
4. Install using `npm install --legacy-peer-deps `
5. Runt `npm run dev`
6. Add missing deps for @sanity/visual-editing manually. ` npm install react react-dom`
7.  `npm run dev` and  🎉
8.  🎉 Nuxt is up and running without error.  

```bash
 WARN  Failed to resolve dependency: @nuxtjs/sanity > @sanity/visual-editing > react, present in 'optimizeDeps.include'                                                                                                                 
 WARN  Failed to resolve dependency: @nuxtjs/sanity > @sanity/visual-editing > react/jsx-runtime, present in 'optimizeDeps.include'
 WARN  Failed to resolve dependency: @nuxtjs/sanity > @sanity/visual-editing > react-dom, present in 'optimizeDeps.include' 
 WARN  Failed to resolve dependency: @nuxtjs/sanity > @sanity/visual-editing > react-dom/client, present in 'optimizeDeps.include'  
```

**Comment by icelandcruiser** [comment]
There was also a hotfix released earlier today 😊 

https://github.com/nuxt-modules/sanity/releases/tag/v1.13.1

**Comment by metaforx** [comment]
I can confirm. Update @nuxtjs/sanity to 1.13.1 solves the issue.
