### ISSUE TITLE
previewDrafts not returning drafts on private production dataSet with new stegaClient loadQuery

### ISSUE THREAD

**Issue by banksy89** [sanity-io/visual-editing#447]
Hi
receiving {data: null} when using perspective previewDrafts on a private production dataset, however when set to published it's returning results on loadQuery.

This seems to be the case when specifically viewing something that is not published. It works with 'published' data, or if a post/article is published, just not if it is in drafts. Within the Sanity Studio Vision the draft articles are searchable in previewDrafts set.

I have checked the token used, and has relevant permissions.

Is there anything that needs to specifically be set ?

The config using:

```
{
  projectId: projectId,
  dataset: 'production',
  apiVersion: '2023-11-01',
  useCdn: false,
  perspective: 'previewDrafts', // published | previewDrafts
  // The 'stega' object groups stega-specific options
  withCredentials: true,
  token: process.env.SANITY_TOKEN
  stega: {
    enabled: true,
    studioUrl: `${STUDIO_ORIGIN}/${sanityDataset}`,
    // High-fidelity control over what strings to stega-encode
    // filter: ({sourcePath, sourceDocument, resultPath, value, filterDefault}) => boolean
    // Rich debug information
    // logger: 
  },
}
```

I have followed everything from these two guides:
https://www.sanity.io/docs/perspectives
https://www.sanity.io/docs/loaders-and-overlays?search=previewDrafts&searchFor=Docs (edited) 

code implementation is essentially this:

```
import {
  createClient,
} from '@sanity/client/stega'
import { createQueryStore } from '@sanity/react-loader'


const config = {
  projectId: projectId,
  dataset: 'production',
  apiVersion: '2023-11-01',
  useCdn: false,
  perspective: 'previewDrafts', // published | previewDrafts
  
  // passing token as produciton is private dataset
  withCredentials: true, // makes no difference
  token: process.env.SANITY_TOKEN

  // The 'stega' object groups stega-specific options
  stega: {
    enabled: true,
    studioUrl: `${STUDIO_ORIGIN}/${sanityDataset}`,
    // High-fidelity control over what strings to stega-encode
    // filter: ({sourcePath, sourceDocument, resultPath, value, filterDefault}) => boolean
    // Rich debug information
    // logger: 
  },
}

const { loadQuery, useQuery } = createQueryStore({
  client: createClient(config),
})

const result = loadQuery(`*[_type == 'content' && url.current == $url ] [0] { "contentId": _id }`, {url: '/example/url'})
```

however, if I use useQuery the response it returns the perspective, but it always appears to be "published" even when setting it as previewDrafts - does that mean it's not handling the previewDrafts perspective if the response perspective is different?

```{
    "loading": false,
    "data": null,
    "sourceMap": {},
    "perspective": "published"
}```

**Comment by stipsan** [comment]
Hi @banksy89! 
For private datasets you need to follow the steps outlined here: https://github.com/sanity-io/visual-editing/tree/main/packages/react-loader#server-only-production-data-fetching-client-side-live-mode
You don't need to set `withCredentials: true,` as it only applies to browser envs, but for private production datasets you must fetch everything server side only on the App Side and the API is designed to avoid accidentally leaking your `token`.
The `token: process.env.SANITY_TOKEN` is important though.
And `perspective: 'published'` should be used, you then switch to `previewDrafts` on the `loadQuery` level:
```ts
import {draftMode} from 'next/headers'

const initial = loadQuery(`*[_type == 'content' && url.current == $url ] [0] { "contentId": _id }`, {url: '/example/url'}, {perspective: draftMode().isEnabled ? 'previewDrafts' : 'published'})


// Later on in your component that has `useQuery`
const {data, error} = useQuery(`*[_type == 'content' && url.current == $url ] [0] { "contentId": _id }`, {url: '/example/url'}, {initial})
if(error) throw error
```

If you're using the Next App Router and RSC then you should use a different import: `import {createQueryStore} from '@sanity/react-loader/rsc'`

**Comment by banksy89** [comment]
@stipsan the project isn't using App Router, actually still using getStaticProps, getServerSideProps. The implementation is actually quite complicated as it's querying through a proxy, but we want some fields to be retrieved from sanity for live editing but via getStaticProps/getServerSideProps (whichever will be the best one for this). 
Will using loadQuery work with this, and following this guide [ https://github.com/sanity-io/visual-editing/tree/main/packages/react-loader#server-only-production-data-fetching-client-side-live-mode](url)? As did try but had no success.

Does useQuery have to be used in conjunction with loadQuery, to have the stega/live edits working?

Is there an example implementation around using this with older nextjs getStaticProps etc. to follow and reference? - or is it more suitable towards app router etc?

**Comment by stipsan** [comment]
Yes, you have to combine `loadQuery` and `useQuery` for it to work.

We'll implement the pattern you need on [this template soon](https://github.com/sanity-io/nextjs-blog-cms-sanity-v3), it's on Pages Router and will stay on Pages Router. It's not yet using Loaders. I'll ping you when it does so you can use it as reference.
