### ISSUE TITLE
Svelte Loader Documentation

### ISSUE THREAD

**Issue by ebrenner-code** [sanity-io/visual-editing#485]
Any estimate on when the docs for the Svelte loader will be complete? Can you point me to ay helpful references or resources?

**Comment by kmelve** [comment]
Hi! We have [docs here](https://www.sanity.io/docs/visual-editing). 

Is there anything you're missing or find unclear?

**Comment by ebrenner-code** [comment]
My apologies, I thought the svelte loader was its own repo that I was opening an issue on. There is missing documentation here: packages/svelte-loader/README.md. I've edited the issue accordingly.

**Comment by rdunk** [comment]
Good timing. The Svelte loader specifically will receive some updates and documentation in the next few hours.

**Comment by ebrenner-code** [comment]
Amazing! I'm super excited to implement this but have been waiting for some guidance.
