### ISSUE TITLE
Presentation Tool re-downloading and re-rendering image assets unnecessarily in Safari

### ISSUE THREAD

**Issue by kennyheard** [sanity-io/visual-editing#511]
**Describe the bug**

When using the new Presentation Tool in Safari, image assets added to a page are re-downloaded every second or so alongside the continuous API requests being made. This causes unsightly content flashes, difficulty selecting content with the overlays, and unnecessary memory usage.

This issue does not appear to happen in Chrome.

**To Reproduce**

1. Clone [template-nextjs-personal-website](https://github.com/sanity-io/template-nextjs-personal-website).
2. In Sanity, create a new page under _Page_.
3. Add an image to the _Body_ field.
4. Monitor the network requests.

**Expected behavior**

- Image assets should not be re-downloaded or re-rendered until they are updated.
- Behaviour across browsers should be consistent.

**Screenshots**

✅ **Chrome**: Network log shows consistent API requests _**without any image requests**_:

<img width="2912" alt="Screenshot 2023-12-07 at 14 08 16" src="https://github.com/sanity-io/visual-editing/assets/48108330/6f7ef18b-a24e-4d68-b413-6a9c0f25b309">

❌ **Safari**: Network log shows consistent API requests **_with constant image requests_**:

<img width="2912" alt="Screenshot 2023-12-07 at 14 08 08" src="https://github.com/sanity-io/visual-editing/assets/48108330/b5a02e6a-effd-4acd-bd91-4b678286ff35">

**Which versions of Sanity are you using?**

```
@sanity/cli (global)        3.21.0 (up to date)
@sanity/demo                 1.0.2 (up to date)
@sanity/image-url            1.0.2 (up to date)
@sanity/overlays             2.1.3 (up to date)
@sanity/preview-url-secret   1.3.1 (up to date)
@sanity/react-loader         1.3.0 (up to date)
@sanity/vision              3.21.0 (up to date)
sanity                      3.21.0 (up to date)
```

**What operating system are you using?**

`macOS 14.0 (23A344)`

**Which versions of Node.js / npm are you running?**

`Node: v20.10.0`
`NPM: v10.2.3`

**Additional context**

`Safari: Version 17.0 (19616.1.27.211.1)`
`Chrome: Version 120.0.6099.62 (Official Build) (arm64)`

**Comment by kennyheard** [comment]
Hey @stipsan. Really appreciate the explanations - all makes perfect sense, thank you.👌🏻

**Comment by xnslx** [comment]
Following. Facing the same issue. The image constantly reloading.

**Comment by stipsan** [comment]
Hey, can ya'll try [v1.7.2](https://github.com/sanity-io/visual-editing/releases/tag/react-loader-v1.7.2) and see if it improves the situation? ☺️

**Comment by kennyheard** [comment]
@stipsan Works perfectly - thanks so much! 🙏🏻
