### ISSUE TITLE
Realtime updates don't work

### ISSUE THREAD

**Issue by donalffons** [sanity-io/visual-editing#567]
Here is a screencast showing an unmodified [template-nextjs-personal-website](https://github.com/sanity-io/template-nextjs-personal-website) running on a brand new sanity project. I did update `NEXT_PUBLIC_SANITY_PROJECT_ID`, `NEXT_PUBLIC_SANITY_DATASET` and `SANITY_API_READ_TOKEN` before launching, of course.

[Screencast from 2023-12-14 09-19-35.webm](https://github.com/sanity-io/visual-editing/assets/33040347/2b115fc9-623e-4000-97cb-a27dd495feaa)

Live updates to the draft / published versions of the documents are not working reliably. Most of the time, they are not working. However, there are network requests that indicate that updated data is received. These requests are apparently made by the front-end page (and not by Sanity studio), since the `query` prop in the `Response` matches the query in the example code.

I originally tried to integrate presentation mode into my existing project by following [the docs](https://www.sanity.io/docs/loaders-and-overlays) and ran into the same issue.

I also verified that the error occurs with both `npm run dev` and `npm run build && npm run start`.

I tested this in Chrome latest, Firefox latest and Chromium 105 (to make sure this isn't a newly introduced issue). All showing the same behavior.

**Which versions of Sanity are you using?**

See the [package.json](https://github.com/sanity-io/template-nextjs-personal-website/blob/main/package.json).

**What operating system are you using?**

Manjaro Linux Vulcan 23.1.0.

**Which versions of Node.js / npm are you running?**

```
9.8.0
v20.5.0
```
(I also just verified the issue is present with node `v18.19.0`)

**Comment by donalffons** [comment]
...just wanted to confirm that this issue is still present with the latest git version of `template-nextjs-personal-website`, even after updating all dependencies to their latest versions.
Is this the right place to report this issue?

**Comment by stipsan** [comment]
This is the right place to report yep :) Is it still happening on `v1.6.4` of `@sanity/react-loader`?
After updating these on `template-nextjs-personal-website` I was no longer able to reproduce this behavior

**Comment by donalffons** [comment]
Yes, it works now! This has been a major blocker for one of our projects. Thanks a ton for fixing this!
