### ISSUE TITLE
Enable stega on draftMode() only.

### ISSUE THREAD

**Issue by IlirEdis** [sanity-io/visual-editing#579]
**Is your feature request related to a problem? Please describe.**

Using [this](https://github.com/sanity-io/template-nextjs-personal-website/tree/main) template, i'm trying to enable stega only on `draftMode()` like this: 

<img width="732" alt="Screenshot 2023-12-22 at 22 12 03" src="https://github.com/sanity-io/visual-editing/assets/128377763/cf60ed37-b57d-472c-99de-35c6046a19a8">

but im getting this typescript error: 
![Screenshot 2023-12-22 at 22 16 18](https://github.com/sanity-io/visual-editing/assets/128377763/a5b88adb-8f8d-4e9f-a61a-47e01652ea42)

Which i think it means you have to add support for this.

Maybe there is another way to do it or i'm missing something?

Thanks!

**Comment by stipsan** [comment]
This is resolved in `@sanity/react-loader@1.8.1`:

```ts
queryStore.loadQuery(query, params, {
  stega: draftMode().isEnabled,
})
```
