### ISSUE TITLE
Overlays showing up in the wrong place in RTL websites

### ISSUE THREAD

**Issue by noamalffasy** [sanity-io/visual-editing#630]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

In an RTL website, the overlays are shown in the wrong place. It seems like they're shifted right.

**To Reproduce**

1. Build a simple website with `dir="rtl"` set at the root.
2. Setup Visual Editing
3. Attempt to hover any element

**Expected behavior**

The overlays should appear around the element rather than being shift to the right.

**Screenshots**
![An overlay to the right of the text it's supposed to wrap](https://github.com/sanity-io/visual-editing/assets/7583207/299e4539-1c46-4953-a77a-9419566deb0f)

**Which versions of Sanity are you using?**

```
@sanity/cli (global)        3.23.4 (up to date)
@sanity/asset-utils          1.3.0 (up to date)
@sanity/icons                2.8.0 (up to date)
@sanity/image-url            1.0.2 (up to date)
@sanity/overlays             2.3.2 (up to date)
@sanity/preview-url-secret   1.4.1 (up to date)
@sanity/react-loader         1.7.0 (up to date)
@sanity/vision              3.23.4 (up to date)
sanity                      3.23.4 (up to date)
```

**What operating system are you using?**
macOS 14.2.1

**Which versions of Node.js / npm are you running?**

```sh
$ npm -v && node -v
10.2.4
v20.9.0
```

**Additional context**

**Additional Note**

I was able to fix this issue by adding to my CSS file:

```css
#sanity-visual-editing {
    direction: ltr;
}
```

Maybe it could be added to the library to help other people building RTL websites?

**Comment by rdunk** [comment]
Thank you for reporting this and providing such a detailed report as well as a fix.

Forcing `ltr` on the overlay as you've suggested seems to be the most sensible solution for now, which has been added in b105aa0ea260f26c26fffa11b8d4b5ea752a95de and should make its way into the next release. I'll close this ticket for now.

Note, we should perhaps consider two other things for localization:
- Moving the "Open in Studio" tab to the left side in RTL layouts.
- A method to provide a translation/override for the "Open in Studio" text (and other upcoming actions).
