### ISSUE TITLE
String conditionals returning incorrect response in Presentation View with fields in nested objects

### ISSUE THREAD

**Issue by fam-studio-dev** [sanity-io/visual-editing#631]
**Describe the bug**

Conditional statements for strings in the Presentation View always return false, despite returning true outside the Presentation View.
This seems to only happen for nested objects and specifically strings. Printing the string returns the expected result. Boolean and url type fields work fine. This is using Next Js v14.0.4 and app router. It works the same in dev environments and on vercel.

**To Reproduce**

1. Make sanity structure:
```
- page
  - array
    - object
      - object
        - string field 
```
2. Fill in field and publish 
3. Setup frontend & visual editing ([this](https://www.sanity.io/guides/nextjs-app-router-live-preview))
3. Console log whether the field equals what it does
e.g. `console.log(asset_type === "image")`

**Expected behavior**

The conditional statement should return true if it is and false if not. 
Should have the same result as outside of Presentation View.

**Screenshots**
![Screenshot 2024-01-07 141812](https://github.com/sanity-io/visual-editing/assets/86244206/77699ba4-8edf-4cd1-8747-8d43ed9c9b83)

Outside Studio 

![Screenshot 2024-01-07 141653](https://github.com/sanity-io/visual-editing/assets/86244206/198212e8-cc2f-4062-9f48-9aacc13afecc)

Inside Studio

![Screenshot 2024-01-07 141752](https://github.com/sanity-io/visual-editing/assets/86244206/90fc541a-93c2-4ca0-82dc-6f86695aa978)

**Which versions of Sanity are you using?**

@sanity/cli (global)       3.23.4
@sanity/image-url        1.0.2
@sanity/overlays           2.3.2
@sanity/react-loader    1.7.0
@sanity/vision               3.23.4

**What operating system are you using?**

Windows 10

**Which versions of Node.js / npm are you running?**

npm:  9.4.1
node: v20.10.0

**Additional context**

**Comment by ndimatteo** [comment]
@fam-studio-dev I ran into this as well, and found this to solve the issue for me: https://www.sanity.io/docs/loaders-and-overlays#f78abaafcf50

You need to clean your strings when using them for comparison like this. The strings are encoded in presentation mode, so even though they visually look like the correct string, there's hidden encoded data in the string that causes it to fail these types of comparisons.

Hope that helps!

**Comment by rdunk** [comment]
Hoping @ndimatteo's solution worked for you @fam-studio-dev.

We're working on improving docs to better describe stega encoding and its implications, reporting issues like this helps us inform that work, so thank you.
