### ISSUE TITLE
Importing @sanity/nuxt-loader creates a "Package import specifier" error

### ISSUE THREAD

**Issue by hbanham** [sanity-io/visual-editing#719]
**Describe the bug**

A "Package import specifier" error appears when viewing a page with @sanity/nuxt-loader:
`Package import specifier "#build/app.config.mjs" is not defined in package /home/projects/github-orsmgg/node_modules/nuxt/package.json imported from /home/projects/github-orsmgg/node_modules/nuxt/dist/app/config.js`

**To Reproduce**

See Stackblitz reproduction: https://stackblitz.com/edit/github-orsmgg?file=package.json,app.vue

1. Create a fresh site using a [Nuxt starter](https://nuxt.new/s/v3)
2. Install nuxt-loader:
`npm install @sanity/nuxt-loader`
4. Import the nuxt-loader package:
`import { createQueryStore, useEncodeDataAttribute } from '@sanity/nuxt-loader';`
5. See error:
![image](https://github.com/sanity-io/visual-editing/assets/61966716/b04ca7e4-26dc-4b92-b657-dd2334a1433c)

**Expected behavior**

I wouldn't expect an error to appear for simply importing the package. If you remove the import, the error disappears.

**Which versions of Sanity are you using?**

@sanity/cli (global) 3.25.0 (up to date)
@sanity/nuxt-loader 1.7.4 (up to date)
@sanity/overlays 2.3.6 (up to date)

**What operating system are you using?**

The error appears on the StackBlitz reproduction, but it also appears on a local project using Windows 10.

**Which versions of Node.js / npm are you running?**

npm: 10.2.3
Node: v18.18.0

**Additional context**

There is a weird interaction I've noticed where it only seems to break on a hard refresh of the page that has the import, or if you navigate to that page using `<a>`, rather than `<NuxtLink>`.  
If you navigate to the page that has the import using `<NuxtLink>`, the error doesn't appear.

I've created a second reproduction to show this:
https://stackblitz.com/edit/github-16x3sm?file=package.json,app.vue,pages%2Findex.vue,pages%2Ftest.vue

I'm new to Sanity and wanted to try out the visual editing feature.

**Comment by Laruxo** [comment]
I have the same issue. It is caused by the `useAsyncData` import [here](https://github.com/sanity-io/visual-editing/blob/c40acaff4e0cd6fb9b1751f8a72e77b278127008/packages/nuxt-loader/src/createQueryStore.ts#L7). As far as I know Nuxt imports should use `#imports` and I see other libs do that (such as [this one](https://github.com/nuxt-modules/prismic/blob/4ce471f6dceadc1f38729234e296dc3429a231eb/src/runtime/usePrismicPreview.ts#L3)). However, I tried changing the import locally and it did not work for me. Instead, it resulted in another error:

```
Package import specifier "#imports" is not defined in package node_modules/@sanity/nuxt-loader/package.json imported from node_modules/@sanity/nuxt-loader/dist/index.js
```

**Comment by rdunk** [comment]
As @blowsie suggested, please migrate to `@nuxtjs/sanity`!
