### ISSUE TITLE
NextJS Client/Server Environment Variables with multiple environments

### ISSUE THREAD

**Issue by dsosborn** [sanity-io/visual-editing#817]
**Is your feature request related to a problem? Please describe.**
When using NextJS with Sanity Preview, the dataset is determined by the environment variable `NEXT_PUBLIC_SANITY_DATASET`. However, Next permanently bakes public env variables into the javascript bundle. Thus, when I build a docker image with the production dataset, it's not possible to run this image in a development environment using my develop dataset. Using `SANITY_DATASET` instead fixes the problem with using alternate datasets at runtime, but breaks preview since it's not available on the client.

To rectify this, I ended up using _both_ env variables, using the public variable as a fallback for client code. This enables Next to generate appropriate content on revalidate, though preview is still stuck on the production dataset:
```
const derivedDataset = process.env.SANITY_DATASET || process.env.NEXT_PUBLIC_SANITY_DATASET;
export const dataset = assertValue( derivedDataset, "Missing environment variable: SANITY_DATASET");
```

**Describe the solution you'd like**
I would like to set a single env variable at runtime that would enable me to use an alternate dataset generate page content on revalidate, and to use in preview mode.

**Describe alternatives you've considered**
My current solution isn't terrible since preview mode in a development environment isn't completely necessary, but it would be nice to at least have a neater way of achieving it with 1 env variable.

**Additional context**
See Slack conversation: https://sanity-io-land.slack.com/archives/C013NG0UF0B/p1706826945250429?thread_ts=1706803404.802629&cid=C013NG0UF0B

**Comment by stipsan** [comment]
Hi, this is out of scope for us as we have no control over how Next.js handles environment variables.
